/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Admin: typeof import('./src/components/Admin.vue')['default']
    copy: typeof import('./src/components/HelloWorld copy.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    PlayerForm: typeof import('./src/components/AdminComponents/Forms/PlayerForm.vue')['default']
    Store: typeof import('./src/components/AdminComponents/store.vue')['default']
  }
}
